services:
  app:
    container_name: api
    build: .
    image: bms-app-backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BMS__APP__PORT}:80"
    networks:
      - bms_net

  db:
    container_name: db
    hostname: ${BMS__DB__HOST}
    image: postgres:18
    environment:
      POSTGRES_USER: ${BMS__DB__USER}
      POSTGRES_PASSWORD: ${BMS__DB__PASS}
      POSTGRES_DB: ${BMS__DB__NAME}
    ports:
      - "${BMS__DB__PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BMS__DB__USER} -d ${BMS__DB__NAME}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - bms_data:/var/lib/postgresql
    networks:
      - bms_net


volumes:
  bms_data:


networks:
  bms_net:
