[project]
name = "bms-em"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi-users[sqlalchemy]>=15.0.4",
    "fastapi[standard]>=0.135.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "sqladmin[full]>=0.23.0",
    "sqlalchemy[asyncio]>=2.0.48",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.7",
]


[tool.ruff.lint]
select = [
    "E4",  # default
    "E7",  # default
    "E9",  # default
    "F",  # default
    "FAST",  # FastAPI specific rules https://docs.astral.sh/ruff/rules/#fastapi-fast
    "B",  # flake8 bugbear https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "A",  # flake8 builtins https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "C4",  # flake8 comprehensions https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "PIE",  # flake8 pie https://docs.astral.sh/ruff/rules/#flake8-pie-pie
    "T20",  # flake8 print https://docs.astral.sh/ruff/rules/#flake8-print-t20
    "PT",  # flake8 pytest style https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    "RET",  # flake8 return https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "SIM",  # flake8 simplify https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "ARG",  # flake8 unused arguments https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "PTH",  # flake8 use pathlib https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "FLY",  # flynt https://docs.astral.sh/ruff/rules/#flynt-fly
    "I",  # isort https://docs.astral.sh/ruff/rules/#isort-i
    "C90",  # mccabe https://docs.astral.sh/ruff/rules/#mccabe-c90
    "W",  # warning https://docs.astral.sh/ruff/rules/#warning-w
    "UP",  # pyupgrade https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "FURB",  # refurb https://docs.astral.sh/ruff/rules/#refurb-furb
    "RUF",  # ruff specific rules https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "TRY",  # tryceratops https://docs.astral.sh/ruff/rules/#tryceratops-try
    "Q004",  # unnecessary quote escape https://docs.astral.sh/ruff/rules/unnecessary-escaped-quote/
    "COM818",  # trailing comma on bare tuple https://docs.astral.sh/ruff/rules/trailing-comma-on-bare-tuple/
]

ignore = [
    "W191",  # tab indentation https://docs.astral.sh/ruff/rules/tab-indentation/
]


[tool.pytest]
asyncio_mode = "auto"
markers = [
    "unit: unit tests",
    "integration: integration tests"
]

[tool.coverage.run]
branch = true

concurrency = [
  "greenlet",
  "thread"
]

[tool.coverage.report]

# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]
