__all__ = [
    "ADD_MEETING_PARTICIPANT_ROUTE_NAME",
    "CREATE_MEETING_ROUTE_NAME",
    "DELETE_MEETING_ROUTE_NAME",
    "GET_MEETINGS_ROUTE_NAME",
    "GET_MEETING_BY_ID_ROUTE_NAME",
    "GET_USER_MEETINGS_ROUTE_NAME",
    "REMOVE_MEETING_PARTICIPANT_ROUTE_NAME",
    "router",
]

from .api_router import (
    ADD_MEETING_PARTICIPANT_ROUTE_NAME,
    CREATE_MEETING_ROUTE_NAME,
    DELETE_MEETING_ROUTE_NAME,
    GET_MEETING_BY_ID_ROUTE_NAME,
    GET_MEETINGS_ROUTE_NAME,
    GET_USER_MEETINGS_ROUTE_NAME,
    REMOVE_MEETING_PARTICIPANT_ROUTE_NAME,
    router,
)
