__all__ = [
    "ADD_USER_TO_TEAM_ROUTE_NAME",
    "ASSIGN_USER_ROLE_ROUTE_NAME",
    "CREATE_TEAM_ROUTE_NAME",
    "GET_TEAMS_ROUTE_NAME",
    "GET_TEAM_MEMBERS_ROUTE_NAME",
    "GET_TEAM_ROUTE_NAME",
    "GET_TEAM_TASKS_ROUTE_NAME",
    "REMOVE_USER_FROM_TEAM_ROUTE_NAME",
    "router",
    "web_router",
]

from .api_router import (
    ADD_USER_TO_TEAM_ROUTE_NAME,
    ASSIGN_USER_ROLE_ROUTE_NAME,
    CREATE_TEAM_ROUTE_NAME,
    GET_TEAM_MEMBERS_ROUTE_NAME,
    GET_TEAM_ROUTE_NAME,
    GET_TEAM_TASKS_ROUTE_NAME,
    GET_TEAMS_ROUTE_NAME,
    REMOVE_USER_FROM_TEAM_ROUTE_NAME,
    router,
)
from .web_router import router as web_router
