name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: ${{ vars.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASS }}
          POSTGRES_DB: ${{ vars.TEST_DB_NAME }}
        ports:
          - ${{ vars.TEST_DB_PORT }}:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: ${{ vars.UV_VERSION }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest tests -x
        env:
          BMS__DB__HOST: localhost
          BMS__DB__PORT: ${{ vars.TEST_DB_PORT }}
          BMS__DB__USER: ${{ vars.TEST_DB_USER }}
          BMS__DB__PASS: ${{ secrets.TEST_DB_PASS }}
          BMS__DB__NAME: ${{ vars.TEST_DB_NAME }}
